name: Build

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  push:
  workflow_dispatch:


jobs:
  build:
    name: Make some packages
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        type:
          - suffix: deb
            image: legleux/ubu_test
            client: apt-get
          - suffix: rpm
            image: legleux/cent_test
            client: rpm
    container:
      image: ${{ matrix.type.image }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: |
          git config --global --add safe.directory /__w/test_repo/test_repo
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo

      - name: Build
        shell: bash
        id: build
        run: |
          filename=cool.${{ matrix.type.suffix }}
          cat /etc/os-release | head -1 > ${filename}
          echo "pkg_sha=$(sha256sum ${filename})" >> $GITHUB_OUTPUT

      - name: Artifact packages
        uses: actions/upload-artifact@v3
        with:
          name: test_repo-${{ steps.vars.outputs.sha_short }}-${{ steps.build.outputs.pkg_sha }}
          path: ${{ github.workspace }}/*.${{ matrix.type.suffix }}
