name: Build

on:
  schedule:
    - cron: '*/15 * * * *'
  push:
  workflow_dispatch:


jobs:
  build:
    name: Make some packages
    outputs:
      release_needed: ${{ steps.check.outputs.release_needed }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        type:
          - suffix: deb
            image: ubuntu:20.04
            client: apt-get
          - suffix: rpm
            image: centos:7
            client: rpm
    container:
      image: ${{ matrix.type.image }}
    steps:
      - name: Build
        shell: bash
        run: |
          touch cool.${{ matrix.type.suffix }}
      - name: Artifact packages
        uses: actions/upload-artifact@v3
        with:
          name: clio_${{ matrix.type.suffix }}_packages
          path: ${{ github.workspace }}/*.${{ matrix.type.suffix }}
